export const types = {
  GET_BEERS_REQUEST: "GET_BEERS_REQUEST",
  GET_BEERS_SUCCESS: "GET_BEERS_SUCCESS",
  GET_BEERS_FAILURE: "GET_BEERS_FAILURE",
  FILTER_BEERS_REQUEST: "FILTER_BEERS_REQUEST",
  FILTER_BEERS_SUCCESS: "FILTER_BEERS_SUCCESS",
  FILTER_BEERS_FAILURE: "FILTER_BEERS_FAILURE",
  SEARCH_BEERS_REQUEST: "SEARCH_BEERS_REQUEST",
  SEARCH_BEERS_SUCCESS: "SEARCH_BEERS_SUCCESS",
  SEARCH_BEERS_FAILURE: "SEARCH_BEERS_FAILURE",
};
